### ISSUE TITLE
Featurereduest: configuration of a subfolder possible?

### ISSUE THREAD

**Issue by Dennis650** [peterus/platformio_dependabot#1]
Hi,

First of all, thank you for this project / this GithubAction.

I have a project, where the platformio project exists in a subfolder of the repository.

Projekt
 - other folders
 - plattformio
    - plattformio.ini

Would it be possible to configure this subfolder in the GitHub action / Docker Container?

Currently I get the error message that no platformio.ini was found.

Greetings Dennis

**Comment by peterus** [comment]
I updated the script for you. can you try the latest release? thanks!

**Comment by Dennis650** [comment]
Hi, thank you very much! In the meantime I restructured my project to make the build work. Maybe I'll go back to the old structure. Greetings Dennis
