### ISSUE TITLE
PR created with no changes

### ISSUE THREAD

**Issue by jeremypoulter** [peterus/platformio_dependabot#4]
I have resently added a workflow using this action and it created 4 PRs, but 3 of these contained no changes, despite the summary/description giving detils of the updates. See:

- OpenEVSE/openevse_esp32_firmware#837
- OpenEVSE/openevse_esp32_firmware#839
- OpenEVSE/openevse_esp32_firmware#840

**Comment by jeremypoulter** [comment]
I think I know the reason: https://github.com/peterus/platformio_dependabot/blob/main/platformio_dependabot/platformio.py#L44-L45
These lines expect the library format to be `library @ 1.2.3`, most of the libraries I use are `library@123` with no spaces.

**Comment by jeremypoulter** [comment]
Note there are also other formats like `library@^1.2.3` for example, see <https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#cmd-pkg-install-specifications>

**Comment by Laxilef** [comment]
Hi @peterus 
Same problem, any news?

**Comment by peterus** [comment]
Thanks @Laxilef for the PR. I think we can close the ticket 😊
